# Configuration options for CNN Regression
experiment_type: 2m_chm

# General configurations
general_crs: "EPSG:32628"

# ATL08 configurations
atl08_dir: '/adapt/nobackup/people/pmontesa/userfs02/data/icesat2/atl08.005/senegal'
atl08_start_year: 2018
atl08_end_year: 2022

# WorldView configurations
wv_data_regex:
  - '/adapt/nobackup/people/mwooten3/Senegal_LCLUC/VHR/CAS/M1BS/*.tif'
  - '/adapt/nobackup/people/mwooten3/Senegal_LCLUC/VHR/ETZ/M1BS/*.tif'
  - '/adapt/nobackup/people/mwooten3/Senegal_LCLUC/VHR/SRV/M1BS/*.tif'

intersection_output_dir: '/adapt/nobackup/projects/ilab/projects/Senegal/CNN_CHM/intersection_metadata_evhrtoa'
tiles_output_dir: '/adapt/nobackup/projects/ilab/projects/Senegal/CNN_CHM/intersection_tiles_evhrtoa'

# Data extraction
tile_buffer: 520

# Model Filename
model_filename: '/adapt/nobackup/projects/ilab/projects/Senegal/CNN_CHM/model/22-27.97.hdf5'
inference_regex: '/adapt/nobackup/people/mcarrol2/LCLUC_Senegal/ForKonrad/Tappan01_WV02_20110430_M1BS_103001000A27E100_data.tif'
inference_save_dir: '/adapt/nobackup/people/jacaraba/development/vhr-cnn-chm/data/cnn_chm_v1'