# Configuration options for CNN Regression
experiment_type: 2m_chm

# ----------------------------------------
# Preprocessing
# ----------------------------------------

# General configurations
general_crs: "EPSG:32628"

# ATL08 configurations
atl08_dir: '/adapt/nobackup/people/pmontesa/userfs02/data/icesat2/atl08.005/senegal'
atl08_start_year: 2018
atl08_end_year: 2022

# WorldView configurations
wv_data_regex:
  - '/adapt/nobackup/people/mwooten3/Senegal_LCLUC/VHR/CAS/M1BS/*.tif'
  - '/adapt/nobackup/people/mwooten3/Senegal_LCLUC/VHR/ETZ/M1BS/*.tif'
  - '/adapt/nobackup/people/mwooten3/Senegal_LCLUC/VHR/SRV/M1BS/*.tif'

# Data extraction
tile_buffer: 40

intersection_output_dir: '/adapt/nobackup/projects/ilab/projects/Senegal/CNN_CHM/intersection_metadata_evhrtoa'
tiles_output_dir: '/adapt/nobackup/projects/ilab/projects/Senegal/CNN_CHM/v3/intersection_tiles_evhrtoa'
landcover_directory: '/adapt/nobackup/projects/3sl/products/landcover/trees.v2'
landcover_preprocessing: False
landcover_postprocessing: True

# ----------------------------------------
# Training
# ----------------------------------------

# data_dir
data_dir: '/adapt/nobackup/projects/ilab/projects/Senegal/CNN_CHM/v3/intersection_tiles_evhrtoa/CAS'
model_dir: '/adapt/nobackup/projects/ilab/projects/Senegal/CNN_CHM/v3/models'
tile_size: 32

# standardization functions: local, global, mixed
standardization: 'local'
batch_size: 64
n_classes: 1
test_size: 0.20
learning_rate: 0.0001
max_epochs: 6000
patience: 10

augment: True
crop: True
seed: 42

model: "tfc.networks.unet_regression.unet_batchnorm_regression(nclass=1, input_size=(32, 32, 8),maps=[16, 32, 64, 128, 256])"
#model: "tfc.networks.unet_regression.get_model_new()"
#loss: 'tf.keras.losses.MeanAbsolutePercentageError()'
loss: 'tf.keras.losses.MeanSquaredError()'
optimizer: tf.keras.optimizers.Adam

metrics:
  - 'tf.keras.metrics.MeanSquaredError()'
  #- 'tf.keras.metrics.RootMeanSquaredError()'
  #- 'tf.keras.metrics.MeanAbsoluteError()'
  - 'tf.keras.metrics.MeanAbsolutePercentageError()'
  #- 'tf.keras.metrics.CosineSimilarity(axis=1)'

callbacks:
  - "tf.keras.callbacks.ModelCheckpoint(save_best_only=True, mode='min', monitor='val_loss', filepath='${model_dir}/{epoch:02d}-{val_loss:.2f}.hdf5')"
  - "tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=4)"
  - "tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=False)"
  #- "tf.keras.callbacks.TerminateOnNaN()"

output_bands:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8

# Model Filename
# model_filename: '/adapt/nobackup/projects/ilab/projects/Senegal/CNN_CHM/model/22-27.97.hdf5'
# model_filename: '/adapt/nobackup/projects/ilab/projects/Senegal/CNN_CHM/v2/intersection_tiles_evhrtoa/CAS/model/41-0.00.hdf5'
model_filename: '/adapt/nobackup/projects/ilab/projects/Senegal/CNN_CHM/v3/models/25-0.00.hdf5'
#inference_regex: '/adapt/nobackup/people/mcarrol2/LCLUC_Senegal/ForKonrad/Tappan01_WV02_20110430_M1BS_103001000A27E100_data.tif'
inference_regex: '/adapt/nobackup/people/mcarrol2/LCLUC_Senegal/ForKonrad/*_data.tif'
inference_save_dir: '/adapt/nobackup/projects/ilab/projects/Senegal/CNN_CHM/v3/output'