# Arguments to pass to the image
ARG TFC_VERSION=0.1.1

FROM nasanccs/tensorflow-caney:latest
LABEL maintainer="jordan.a.caraballo-vega@nasa.gov"

RUN pip install git+https://github.com/nasa-nccs-hpda/tensorflow-caney.git@0.1.1


HEALTHCHECK NONE
ENTRYPOINT [""]
